[2025-03-10T05:01:12.461+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T05:01:12.480+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:38:05.165184+00:00 [queued]>
[2025-03-10T05:01:12.488+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:38:05.165184+00:00 [queued]>
[2025-03-10T05:01:12.489+0600] {taskinstance.py:2867} INFO - Starting attempt 2 of 1
[2025-03-10T05:01:12.605+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-03-09 18:38:05.165184+00:00
[2025-03-10T05:01:12.614+0600] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-10T05:01:12.620+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_e2e_dag', 'extract_data_task', 'manual__2025-03-09T18:38:05.165184+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/RT_data_extract_and_write_to_pg.py', '--cfg-path', '/tmp/tmpq8szix3y']
[2025-03-10T05:01:12.621+0600] {standard_task_runner.py:105} INFO - Job 33: Subtask extract_data_task
[2025-03-10T05:01:12.624+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5919) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T05:01:12.625+0600] {standard_task_runner.py:72} INFO - Started process 6110 to run task
[2025-03-10T05:01:12.668+0600] {task_command.py:467} INFO - Running <TaskInstance: real_time_e2e_dag.extract_data_task manual__2025-03-09T18:38:05.165184+00:00 [running]> on host shamim-X541UV
[2025-03-10T05:01:12.736+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_e2e_dag' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T18:38:05.165184+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T18:38:05.165184+00:00'
[2025-03-10T05:01:12.738+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T05:01:12.738+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T05:01:12.739+0600] {logging_mixin.py:190} INFO - Current task name:extract_data_task state:running start_date:2025-03-09 23:01:12.480692+00:00
[2025-03-10T05:01:12.739+0600] {logging_mixin.py:190} INFO - Dag name:real_time_e2e_dag and current dag run status:running
[2025-03-10T05:01:12.739+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T05:01:16.053+0600] {java_gateway.py:2273} INFO - Callback Server Starting
[2025-03-10T05:01:16.053+0600] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 33231)
[2025-03-10T05:04:20.619+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_data_extract_and_write_to_pg.py", line 62, in extract_data
    .awaitTermination()
     ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 67fda593-71b8-46f0-baf4-97a195e0f5b3, runId = 8dee46e8-11ff-43e2-b614-b5521be9c2eb] terminated with exception: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeTopics
[2025-03-10T05:04:20.635+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T05:04:20.636+0600] {logging_mixin.py:190} INFO - Task start:2025-03-09 23:01:12.480692+00:00 end:2025-03-09 23:04:20.635442+00:00 duration:188.15475
[2025-03-10T05:04:20.636+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data_task> dag:<DAG: real_time_e2e_dag> dagrun:<DagRun real_time_e2e_dag @ 2025-03-09 18:38:05.165184+00:00: manual__2025-03-09T18:38:05.165184+00:00, state:running, queued_at: 2025-03-09 18:38:05.222089+00:00. externally triggered: True>
[2025-03-10T05:04:20.641+0600] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = 67fda593-71b8-46f0-baf4-97a195e0f5b3, runId = 8dee46e8-11ff-43e2-b614-b5521be9c2eb] terminated with exception: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeTopics
[2025-03-10T05:04:20.641+0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=real_time_e2e_dag, task_id=extract_data_task, run_id=manual__2025-03-09T18:38:05.165184+00:00, execution_date=20250309T183805, start_date=20250309T230112, end_date=20250309T230420
[2025-03-10T05:04:20.691+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T05:04:20.691+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task extract_data_task ([STREAM_FAILED] Query [id = 67fda593-71b8-46f0-baf4-97a195e0f5b3, runId = 8dee46e8-11ff-43e2-b614-b5521be9c2eb] terminated with exception: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeTopics; 6110)
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/RT_data_extract_and_write_to_pg.py", line 62, in extract_data
    .awaitTermination()
     ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/shamim/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = 67fda593-71b8-46f0-baf4-97a195e0f5b3, runId = 8dee46e8-11ff-43e2-b614-b5521be9c2eb] terminated with exception: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: describeTopics
[2025-03-10T05:04:20.798+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T05:04:20.837+0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T05:04:20.841+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
