[2025-03-10T20:57:44.997+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T20:57:45.032+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: E2E_kafka_producer_data_ETL_dag.load_clean_data_into_pg_task manual__2025-03-10T14:57:05.395673+00:00 [queued]>
[2025-03-10T20:57:45.053+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: E2E_kafka_producer_data_ETL_dag.load_clean_data_into_pg_task manual__2025-03-10T14:57:05.395673+00:00 [queued]>
[2025-03-10T20:57:45.053+0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-10T20:57:45.088+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_clean_data_into_pg_task> on 2025-03-10 14:57:05.395673+00:00
[2025-03-10T20:57:45.133+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'E2E_kafka_producer_data_ETL_dag', 'load_clean_data_into_pg_task', 'manual__2025-03-10T14:57:05.395673+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/E2E_ETL_pipeline.py', '--cfg-path', '/tmp/tmp3n9e7wpl']
[2025-03-10T20:57:45.138+0600] {standard_task_runner.py:105} INFO - Job 57: Subtask load_clean_data_into_pg_task
[2025-03-10T20:57:45.184+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=80210) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T20:57:45.196+0600] {standard_task_runner.py:72} INFO - Started process 80242 to run task
[2025-03-10T20:57:45.239+0600] {task_command.py:467} INFO - Running <TaskInstance: E2E_kafka_producer_data_ETL_dag.load_clean_data_into_pg_task manual__2025-03-10T14:57:05.395673+00:00 [running]> on host shamim-X541UV
[2025-03-10T20:57:45.448+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='E2E_kafka_producer_data_ETL_dag' AIRFLOW_CTX_TASK_ID='load_clean_data_into_pg_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T14:57:05.395673+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T14:57:05.395673+00:00'
[2025-03-10T20:57:45.456+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T20:57:45.457+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T20:57:45.457+0600] {logging_mixin.py:190} INFO - Current task name:load_clean_data_into_pg_task state:running start_date:2025-03-10 14:57:45.033652+00:00
[2025-03-10T20:57:45.461+0600] {logging_mixin.py:190} INFO - Dag name:E2E_kafka_producer_data_ETL_dag and current dag run status:running
[2025-03-10T20:57:45.462+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T20:57:45.464+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/E2E_ETL_pipeline.py", line 115, in insert_df_into_pg
    df = kwargs['ti'].xcom_pull(key='DataFrame', task_ids='transform_data_task')
         ~~~~~~^^^^^^
TypeError: tuple indices must be integers or slices, not str
[2025-03-10T20:57:45.482+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T20:57:45.483+0600] {logging_mixin.py:190} INFO - Task start:2025-03-10 14:57:45.033652+00:00 end:2025-03-10 14:57:45.481453+00:00 duration:0.447801
[2025-03-10T20:57:45.483+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_clean_data_into_pg_task> dag:<DAG: E2E_kafka_producer_data_ETL_dag> dagrun:<DagRun E2E_kafka_producer_data_ETL_dag @ 2025-03-10 14:57:05.395673+00:00: manual__2025-03-10T14:57:05.395673+00:00, state:running, queued_at: 2025-03-10 14:57:05.411916+00:00. externally triggered: True>
[2025-03-10T20:57:45.484+0600] {logging_mixin.py:190} INFO - Failure caused by tuple indices must be integers or slices, not str
[2025-03-10T20:57:45.485+0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=E2E_kafka_producer_data_ETL_dag, task_id=load_clean_data_into_pg_task, run_id=manual__2025-03-10T14:57:05.395673+00:00, execution_date=20250310T145705, start_date=20250310T145745, end_date=20250310T145745
[2025-03-10T20:57:45.534+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T20:57:45.535+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task load_clean_data_into_pg_task (tuple indices must be integers or slices, not str; 80242)
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/Real_Time_Big_Data_Airflow/dags/E2E_ETL_pipeline.py", line 115, in insert_df_into_pg
    df = kwargs['ti'].xcom_pull(key='DataFrame', task_ids='transform_data_task')
         ~~~~~~^^^^^^
TypeError: tuple indices must be integers or slices, not str
[2025-03-10T20:57:45.585+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T20:57:45.683+0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T20:57:45.710+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
